### ISSUE TITLE
Allow fab set to add non-existing annotations

### ISSUE THREAD

**Issue by samiyaakhtar** [Microsoft/fabrikate#124]
**As an operator:** I'd like to see additional metadata in the generated yaml about details such as author, time, release url, user who triggered the release etc. All this information is available as part of the release pipeline in Azure DevOps, it's a matter of leveraging it to include more information for auditing purposes. 

Fabrikate could provide a command on a subcomponent/environment that lets you specify a collection of key/values to set at annotations. Fabrikate could determine if annotations already exist and handle appending additional key/values and avoiding duplicates. Currently, `fab set` is able to modify yaml to update image tags or similar, but it's missing the functionality to add an annotation if it doesn't exist. 

<pre>
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  <b>annotations:
    bedrock/releaseUrl: "https://dev.azure.com/abrig/efd47cfd-d35f-40ba-b424-e1ab432fdc68/_release?releaseId=37"
    bedrock/triggeredBy: "Andre Briggs"</b>
    ...
</pre>

**Additional context:** [here](https://github.com/Microsoft/bedrock/issues/315)

**Comment by timfpark** [comment]
My current thinking on this is that we should essentially extend the ComponentConfig model to enable this - this would enable us to have per environment and per directory tree injections.  I am thinking something like this in the config file:

```
inject:
  metadata:
    annotations:
      "bedrock/releaseUrl": "https://dev.azure.com/abrig/efd47cfd-d35f-40ba-b424-e1ab432fdc68/_release?releaseId=37"
      "bedrock/triggeredBy": "Andre Briggs"
subcomponents:
  cloud-native:
```

where this could be set from the command line in the same manner as `set` is used for config, but with a command called `inject`:

```
$ fab inject --environment prod "metadata.annotations.bedrock/triggeredBy"="Andre Briggs"
```

These injections would be done after generation on all resource manifests and would override existing values in charts.

@samiyaakhtar @andrebriggs Would you mind doing a design review of the above and letting me know if you think it would meet your needs?  Let me know if you can think of a better way of doing this as well - I feel like this design is good but not great.
