### ISSUE TITLE
Unable to create if else condition in config

### ISSUE THREAD

**Issue by edaena** [Microsoft/fabrikate#167]
**Describe the bug:**
Unable to create if else condition in config.

**To Reproduce:**
Add an if condition like the one in the selector below:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc-stage
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}
```

**Expected behavior:**
The correct files are generated

**Seen:**
```
ERRO[26-04-2019 15:13:14] helm template failed with: Error: render error in "service-chart/templates/service-stage.yaml": template: service-chart/templates/service-stage.yaml:9:11: executing "service-chart/templates/service-stage.yaml" at <eq .Values.productio...>: error calling eq: invalid type for comparison

```

**Additional context:**
Bug encountered as part of the work to enable blue-green deployment for project jackson: [project-jackson/service-stage.yaml](https://github.com/andrebriggs/fabrikate-sample-app/blob/traefik_bg/services/project-jackson/service-chart/templates/service-stage.yaml)
