### ISSUE TITLE
Quick Start on main README.md broken

### ISSUE THREAD

**Issue by evanlouie** [microsoft/fabrikate#185]
**Describe the bug:** 
reported by: @buzzfrog

In our main quickstart, the following config causes an error when materialized and `k apply...` is run because the `services` namespaces doesn't exist and no static manifest exists to create it.

```yaml
subcomponents:
  simple-service:
    namespace: services
    config:
      gateway: my-ingress.istio-system.svc.cluster.local
      service:
        dns: simple.mycompany.io
        name: simple-service
        port: 80
      configMap:
        PORT: 80
      tiers:
        canary:
          image: "timfpark/simple-service:441"
          replicas: 1
          weight: 10
          port: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"

        stable:
          image: "timfpark/simple-service:440"
          replicas: 3
          weight: 90
          port: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
```

**To Reproduce:** Run through the quickstart up until trying to `k apply` the materialized manifests.

**Expected behavior:** Quickstart is completable.

**Screenshots:**

**Additional context:**

**Desktop (please complete the following information):**

- OS:

**Additional context**
