### ISSUE TITLE
Can't specify remote components in root component (non subcomponent)

### ISSUE THREAD

**Issue by evanlouie** [microsoft/fabrikate#212]
**Describe the bug:** Am not able to use `method: git` with an `source: <some-git-repo>` on the root component

**To Reproduce:**

run fab install on the following component:

```yaml
name: cloud-native # In-cluster monitoring and service-mesh tooling
source: https://github.com/microsoft/fabrikate-definitions.git
path: definitions/fabrikate-cloud-native
method: git
```

**Expected behavior:** either install that component or explicitly say in docs that the root component cannot be an another external component

**Screenshots:**

**Additional context:**

**Desktop (please complete the following information):**

- OS:

**Additional context**
