### ISSUE TITLE
before-generate & after-generate hooks

### ISSUE THREAD

**Issue by evanlouie** [Microsoft/fabrikate#22]
As an operator, I want to have `before-generate` and `after-generate` hooks so that I can do necessary install/cleanup jobs before/after generating helm templates.

AC: support the following component:

```
name: istio-system
generator: static
path: "./manifests"
hooks:
  before-install:
    - wget https://github.com/istio/istio/releases/download/1.0.5/istio-1.0.5-linux.tar.gz
    - tar xvf istio-1.0.5-linux.tar.gz -C tmp
  after-install:
    - rm istio-1.0.5-linux.tar.gz
  before-generate:
    - echo "I DO SOMETHING"
  after-generate:
    - rm -rf tmp
subcomponents:
  - name: istio
    generator: helm
    path: "./tmp/istio-1.0.5/install/kubernetes/helm/istio"
```
