### ISSUE TITLE
Helm Template outputting warnings; breaking namespace injection

### ISSUE THREAD

**Issue by evanlouie** [microsoft/fabrikate#232]
**Describe the bug:** Some charts will output warnings in the output of `helm template`, such as:

```
2019/08/01 15:22:41 Warning: Merging destination map for chart 'kafka'. The destination item 'resources' is a table and ignoring the source 'resources' as it has a non-table value of: <nil>
```

This breaks the namespace injection functionality as it attempts to unmarshal the manifests into `map[interface{}]interface{}` and the top entry is just a string.

**To Reproduce:**

component.yaml:

```yaml
name: "kafka"
subcomponents:
  - name: "confluent-schema-registry"
    type: "helm"
    source: "https://kubernetes-charts-incubator.storage.googleapis.com/"
    method: "helm"
    path: "schema-registry"
```

config/common.yaml:

```yaml
config:
subcomponents:
  confluent-schema-registry:
    namespace: "kafka"
    injectNamespace: true
```

Run: 

```
./fab install
./fab generate
``` 

**Expected behavior:** The warnings are munged and `./fab generate` outputs the warnings to stdout but generates the manifests which are `map[interface{}]interface{}`

**Screenshots:**

**Additional context:**

**Desktop (please complete the following information):**

- OS:

**Additional context**
