### ISSUE TITLE
Change to "type" instead of "generator" for examples in README.md

### ISSUE THREAD

**Issue by buzzfrog** [microsoft/fabrikate#237]
**Describe the bug:**
In 1.0 of Fabrikate we changed component definitions from "generate" to "type". But in the documentation "generate" is still in the examples.

**To Reproduce:**

**Expected behavior:**
```yaml
name: "cloud-native"
type: static
path: "./manifests"
subcomponents:
```
**Screenshots:**

**Additional context:**

**Desktop (please complete the following information):**
- OS: Linux Mint 19.2

**Additional context**
