### ISSUE TITLE
Add the possibility to generate a kustomization.yaml

### ISSUE THREAD

**Issue by basvandenbrink** [microsoft/fabrikate#239]
**As a:**
Fabrikate user

**I want:**
To generate a kustomization.yaml per environment that includes all generated Kubernetes YAML as resources files for that enviroment.

**So that:**
I can use `kubectl apply -k <environment_dir>` to apply the resources to the cluster.

`kubectl apply -k` has support for ordering the Kubernetes resources. This would solve issues like #20.

**Describe the solution you'd like:**
Implement a `-k` or `--kustomize` option for `fab generate`. If this option is set, fabrikate will generate a *kustomization.yaml* file for every environment:

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- <component_a>.yaml
- <component_b>.yaml
- <component_c>.yaml
```

**Describe alternatives you've considered:**
Describing all namespaces as a static component. Then, when executing `fab generate`, a separate file will be created with the namespaces. Then, I could first do `kubectl apply <namespaces_file>.yaml` and then do `kubectl apply .`. However, this would only solve the namespace not ready problem. There could be other ordering problems that kustomize solve and that are not address by this alternative.

**Additional context:**
