### ISSUE TITLE
Invalid YAML removes most of the content of HLD

### ISSUE THREAD

**Issue by Lybecker** [microsoft/fabrikate#241]
**Describe the bug:**
Adding an environment variable with no space between the key and the value removes most of the content of the HLD YAML file.

**To Reproduce:**
1. Make a /config/common.yaml  like this:
```
subcomponents:
  anotherservice:
    config:
      image:
        tag: "744"
      replicaCount: 1
  screenprofiler:
    config:
      envVar:
        important: true
        fabshouldfail: true
        is_this_a_bug: definitely
        culprit:"this is where it all goes wrong due to the lack of space between key and value"
      image:
        repository: somewheregood.azurecr.io/screenprofiler
        tag: "73"
      replicaCount: 1
```
The subcomponents | screenprofiler | envVar | culprit is the problem

2. Execute fabricate
```
./fab set --subcomponent screenprofiler image.tag=747
```
3. Fabricate removes most of the HLD file:
```
subcomponents:
  screenprofiler:
    config:
      image:
        tag: "747"
```

**Expected behavior:**
Fabricate should fail, as the YAML is invalid

OR

subcomponents | screenprofiler | image | tag is set to 747

Like 

```
subcomponents:
  anotherservice:
    config:
      image:
        tag: "744"
      replicaCount: 1
  screenprofiler:
    config:
      envVar:
        important: true
        fabshouldfail: true
        is_this_a_bug: definitely
        culprit:"this is where it all goes wrong due to the lack of space between key and value"
      image:
        repository: somewheregood.azurecr.io/screenprofiler
        tag: "747"
      replicaCount: 1
```

**Desktop (please complete the following information):**

Reproduced on:
 - WSL Windows 10 OS Build 18362.295
 - Azure DevOps Agent Hosted Ubuntu 1604

fab version 0.15.2

Execute via Azure DevOps Agent like so:
curl https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh > build.sh
chmod +x ./build.sh

curl https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/release.sh > release.sh
chmod +x ./release.sh
