### ISSUE TITLE
Duplicate entries in generated file when passing common as config

### ISSUE THREAD

**Issue by basvandenbrink** [microsoft/fabrikate#266]
**Describe the bug:**
Fabrikate writes duplicate entries in a very specific case at a very specific place, when invoking as `fab generate common`. This does not happen when invoking as `fab generate` 

**To Reproduce:**
Create a fabrikate component as follows.

_component.yaml_:
```yaml
name: fab-duplicate-issue
subcomponents:
- name: grafana
  type: component
  generator: helm
  source: https://github.com/helm/charts
  method: git
  path: stable/grafana
  branch: master
```

_config/common.yaml_:
```yaml
subcomponents:
  grafana:
    config:
      datasources:
        datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.logging
              access: proxy
              isDefault: true
```
Then, execute `fab generate common`. The _ConfigMap_ part of the generated YAML is as follows (skipped irrelevant parts).
```yaml
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: default
  <skipped>
data:
  <skipped>
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-server.logging
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-server.logging
```

**Expected behavior:**
It is expected that the output would be the same when executing `fab generate`. The duplicate entry would not occur and the result is as follows.

```yaml
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: default
  <skipped>
data:
  <skipped>
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-server.logging
```

**Desktop (please complete the following information):**

- OS: Fedora 30

**Additional context**
- Fabrikate: 0.16.2
- Helm: 2.13.1
- Grafana chart version: 3.9.1
