### ISSUE TITLE
Ability to include / exclude subcomponents based on config

### ISSUE THREAD

**Issue by timfpark** [microsoft/fabrikate#277]
As an operator I would like to dynamically be able to include or exclude components based on configuration.  For example, if I had a very large number of distributed locations and wanted to enable app A in 20% of them and app B in 80% of them.

Right now, Fabrikate does not have a mechanism to accomplish this with configuration.  This issue tracks the ability to enable or disable components or subcomponents based on config.

**Comment by maarek** [comment]
@timfpark  Are you thinking something along the lines of...

Adding `included` to the schema definition for config with a default value of `true` for backwards compatibility.

commom.yaml
```yaml
config:
included: "true"
subcomponents:
  jaeger:
    namespace: "jaeger"
    injectNamespace: true
    config:
      collector:
        annotations:
          sidecar.istio.io/inject: "false"
```

`fab generate` would generate the component + sub-component. 

azure.yaml
```yaml
config:
subcomponents:
  jaeger:
    included: "false"
```

`fab generate azure` would generate the base component but not the jaeger sub-component.
