### ISSUE TITLE
Ability to override source branches in config files

### ISSUE THREAD

**Issue by Chipzter** [microsoft/fabrikate#283]
As an operator, I would like to be able to specify a development branch of a component _helm chart_ repo so that I can test changes to the _helm charts_ before PRing them to the master branch.

In support of this, add a branch field to the component _config_ spec such that I can override which branch each subcomponent definition or helm chart is cloned from per environment.

example config/test.yaml:
```
subcomponents:
  myfeed:
    branch: develop
    config:
      image:
        tag: 1.0.7
```

A possible work-around could be to maintain a separate HLD repository (and its target manifest repo) that references the development branch(es) instead of the master branch(es), but that feels like it would defeat the beauty of the bedrock framework.
