### ISSUE TITLE
fab add may not be idempotent

### ISSUE THREAD

**Issue by mtarng** [microsoft/fabrikate#294]
**Describe the bug:**
When calling `fab add` it excludes `type: component` at the top level of the `component.yaml`.
Subsequently, if you run the same command again, `type:component` will be added as, I suspect, it's being added to the object when loading from the `component.yaml` file.

**To Reproduce:**
- Run `fab add someservice --path ./someservice --method local --type component`
- cat component.yaml:
  ```
  name: somepath
  subcomponents:
  - name: someservice
    type: component
    method: local
    path: ./someservice
  ```
- rerun `fab add someservice --path ./someservice --method local --type component`
- cat component.yaml:
  ```
  name: somepath
  type: component
  subcomponents:
  - name: someservice
    type: component
    method: local
    path: ./someservice
  ```
notice `type: component` has been added at the top level.
**Expected behavior:**
`type: component` should probably be added on the first run.

**Screenshots:**

**Additional context:**

**Desktop (please complete the following information):**

- OS:
macOS
**Additional context**
