### ISSUE TITLE
Fabrikate config merging algorithm does not produce intended configuration

### ISSUE THREAD

**Issue by bnookala** [Microsoft/fabrikate#41]
When building the Cloud Native stack (https://github.com/timfpark/fabrikate-cloud-native/), `fab` is producing the wrong config through the process of merging, thus generating charts that deploy too many resources. 

Example common.json from `fabrikate-jaeger`:

```json
{
    "config": {},
    "subcomponents": {
        "jaeger": {
            "config": {
                "namespace": "jaeger"
            }
        }
    }
}
```

Example prod.json from `fabrikate-jaeger`:
```json
{
    "config": {},
    "subcomponents": {
        "jaeger": {
            "config": {
                "provisionDataStore": {
                    "cassandra": false,
                    "elasticsearch": true
                },
                "storage": {
                    "type": "elasticsearch"
                },
                "elasticsearch": {
                    "rbac": {
                        "create": true
                    }
                },
                "spark": {
                    "enabled": true
                },
                "collector": {
                    "replicaCount": 5
                },
                "query": {
                    "replicaCount": 2
                }
            }
        }
    }
```

prod.yaml from cloud native stack:
```yaml
  jaeger:
    config:
    subcomponents:
      jaeger:
        config:
          spark:
            enabled: true
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 256m
                memory: 128Mi
          provisionDataStore:
            cassandra: false
            elasticsearch: false
          storage:
            type: "elasticsearch"
            elasticsearch:
              scheme: "http"
              host: "elasticsearch-client.elasticsearch.svc.cluster.local"
              port: 9200
          collector:
            replicaCount: 3
            resources:
              limits:
                cpu: 1
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
          query:
            replicaCount: 2
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 256m
                memory: 128Mi
          agent:
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 256m
                memory: 128Mi
```

As you can see, the `prod.yaml` from the cloud native stack has a section `provisionDataStore`, that disables provisioning cassandra or elasticsearch:
```yaml
          provisionDataStore:
            cassandra: false
            elasticsearch: false
 ```

but the merged configuration retains the use of `elasticsearch: true` from fabrikate-jaeger's prod.json file. Output logs from `fab generate prod --verbose` in the cloud native stack:

```
INFO[01-02-2019 14:30:25] 💾  Loading components/jaeger/component.json
INFO[01-02-2019 14:30:25] 💾  Loading components/jaeger/config/prod.json
INFO[01-02-2019 14:30:25] 💾  Loading components/jaeger/config/common.json
INFO[01-02-2019 14:30:25] 🚚  generating component 'fabrikate-jaeger' statically from path ./manifests
DEBU[01-02-2019 14:30:25] Iterating component fabrikate-jaeger with config:
config: {}
subcomponents:
  jaeger:
    config:
      agent:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 128Mi
      collector:
        replicaCount: 3
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      elasticsearch:
        rbac:
          create: true
      namespace: jaeger
      provisionDataStore:
        cassandra: false
        elasticsearch: true
      query:
        replicaCount: 2
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 128Mi
      spark:
        enabled: true
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 128Mi
      storage:
        elasticsearch:
          host: elasticsearch-client.elasticsearch.svc.cluster.local
          port: 9200
          scheme: http
        type: elasticsearch
    subcomponents: {}
```
