### ISSUE TITLE
Fabrikate emiting 'data: null

### ISSUE THREAD

**Issue by timfpark** [Microsoft/fabrikate#48]

**Comment by timfpark** [comment]
When generating the resource manifests for the prometheus-grafana stack, it emits a data:null for one of the ConfigMaps of the deployment.  This seems unexpected, although the stack works afterwards.  G 
```
apiVersion: v1
data: null
kind: ConfigMap
metadata:
  labels:
    app: grafana
    chart: grafana-1.26.1
    dashboard-provider: default
    heritage: Tiller
    release: grafana
  name: grafana-dashboards-default
  namespace: grafana
```
