### ISSUE TITLE
fabrikate should be able to handle custom chart repositories

### ISSUE THREAD

**Issue by bnookala** [Microsoft/fabrikate#64]
Some infrastructures (like istio) host their own chart repositories, and have subchart dependencies which pull from them. Stack maintainers should be able to specify custom chart repositories that their stack relies on so that `helm dependency update` or `helm fetch` can successfully be run. 

Example component.yaml: 

```
name: istio
generator: helm
repository:
    - istio.io
       https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
    - incubator
       https://kubernetes-charts-incubator.storage.googleapis.com/
…
```

Perhaps the repository can be added during `fab install` and dependency updates, and removed right after, to avoid cluttering the user's helm repository list.

**Comment by timfpark** [comment]
Here's what I would propose: 

```
name: istio
generator: helm
repositories:
    istio.io: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
    incubator: https://kubernetes-charts-incubator.storage.googleapis.com/
…
```

I am also proposing a migration of the current `repo` field to designate where to clone the helm chart from to instead use the same `source` and `method` fields that components use to load themselves to prevent confusion between the above `repositories`  and `repo` and simplify the component model.

The proposal would be to depreciate `repo` over one version with warnings, automatically migrating the value in this field to `source` and adding a `method` of git automatically until the migration is complete. 

Thoughts @bhargav and @evanlouie?
