### ISSUE TITLE
Add ability to bundle tool hooks with Fabrikate components

### ISSUE THREAD

**Issue by timfpark** [Microsoft/fabrikate#66]
As an operator, after utilizing a publicly available Fabrikate component like prometheus-grafana, I want to be able to be able to easily bring up the grafana dashboard without resorting to manually typing something like this:

```
export GRAFANA_POD=
`sleep 1 && open http://localhost:3000/d/4XuMd2Iiz/kubernetes-cluster-prometheus?orgId=1` &
kubectl --namespace grafana port-forward $GRAFANA_POD 3000
```

Instead, as an operator, I want to be able to do something like this:

```
$ fab run grafana
```

where behind the scenes the author of a Fabrikate component has added a `command` item to the component:

```
name: "prometheus-grafana"
generator: "static"
path: "./manifests"
subcomponents:
- name: "grafana"
  generator: "helm"
  repo: "https://github.com/helm/charts"
  path: "stable/grafana",
  commands:
    grafana:
    - sleep 1 && open http://localhost:3000/d/4XuMd2Iiz/kubernetes-cluster-prometheus?orgId=1 &
    - kubectl --namespace grafana port-forward $(kubectl get pods -n grafana -o jsonpath="{.items[0].metadata.name}") 3000
- name: "prometheus"
  generator: "helm"
  repo: "https://github.com/helm/charts"
  path: "stable/prometheus"
```
