### ISSUE TITLE
Fab should support adjusting config values

### ISSUE THREAD

**Issue by samiyaakhtar** [Microsoft/fabrikate#84]
`fab generate` should support runtime parameters which overwrite any config found in the merged configs found in the HLD. This will help us update image tag and repository when changes are made in ACR. Example `fab generate <env> -p <jsonpath>=<value> -p <jsonpath>=<value>`

**Comment by evanlouie** [comment]
CICD User story:

As an operator, I want my CICD pipeline to be able to generate a newly tagged image of my application and inject the new tag into my HLD at `generate` time so that I do not have to manually modify my HLD repository to deploy new versions of my application.

**Comment by andrebriggs** [comment]
> CICD User story:
> 
> As an operator, I want my CICD pipeline to be able to generate a newly tagged image of my application and inject the new tag into my HLD at `generate` time so that I do not have to manually modify my HLD repository to deploy new versions of my application.

@evanlouie this is good. I think the scenario should be expanded to to any variable. Image tag can be one. It could be replicas count (auto scaling scenario), or something else. 

@samiyaakhtar what do you mean by jsonpath? Can you provide an example?

**Comment by evanlouie** [comment]
@andrebriggs i was using image tag just as an example. JSON path is just a way to parse paths in JSON objects (https://github.com/json-path/JsonPath)

**Comment by timfpark** [comment]
I feel like there is a deeper level issue in Fabrikate that is driving this because, after a day of thinking about it (and a little implementation), this feels like a workaround.  

If we took this approach we break our promise to the operations team to have a commits in both the high level definition and resource manifest repos reflect what we believe is running in the cluster.

To flush out what the right solution is here, why do we not want to check in a change to the HLD repo with each container build (what is the downside we believe there is to this approach)?

**Comment by dtzar** [comment]
What if we have something like `fab set <env> -p <jsonpath>=value` where `fab set` actually updates the corresponding JSON values in the HLD?  This could be followed up by an automated `git commit -am` and `git push`

Aside from the slowness issue #62 I think the reality is there needs to be a relatively easy way to automate updates to the HLD.  There are various use cases where the cluster and/or manifest repo are updated and need to be reflected in the HLD so the actual cluster state doesn't get improperly overridden on the next push to the manifest repo from the HLD `fab generate`.

**Comment by timfpark** [comment]
Agreed - the "tower of configuration" in particular is hard for humans to grok - and this plays into the suggestion that @bnookala had around adding more scaffolding to make operations like this easier for normal humans.

There is some complexity around where this configuration value should be applied, since configuration values for any component can be applied at the component it applies to or any component above it. For example, if you wanted to set the configuration value of `data.replicas` to `4` for a `elasticsearch` subcomponent but only in your high level definition you need to specify both the component you want to provide configuration for and also where in the hierarchy of your hld you want to specify this configuration.

For example, assuming your hld top level component was named `my-microservices`, we could do this with something like this:

```
$ fab set my-microservices/common -c elasticsearch  -p data.replicas=3 -p another.value=8
```

`fab` would then crawl the hierarchy to figure out that the `elasticsearch` component was at `cloud-native/elasticsearch-fluentd-kibana/elasticsearch` in the hierarchy and therefore that it should generate the following config spec:

```
  cloud-native:
    subcomponents:
      elasticsearch-fluentd-kibana:
        subcomponents:
          elasticsearch:
            config:
              data:
                replicas: 4
```

and place it in the `subcomponents` block of `~/config/common.yaml`:

```
...
subcomponents:
  cloud-native:
    subcomponents:
      elasticsearch-fluentd-kibana:
        subcomponents:
          elasticsearch:
            config:
              data:
                replicas: 4
      istio:
        subcomponents:
          kiali-secret:
            config:
              username: admin
              passphrase: "superSECR3T"
...
```

Thoughts?
