### ISSUE TITLE
Fabrikate should be able to add subcomponents.

### ISSUE THREAD

**Issue by timfpark** [Microsoft/fabrikate#97]
As a person in a devops role, it would make my job of developing a Fabrikate definition easier if I could easily add subcomponents to a component without having to manually add them myself.

For example, let's say I currently had the following `component.yaml`:

```
name: "prometheus-grafana"
generator: "static"
path: "./manifests"
subcomponents:
- name: "prometheus"
  type: "chart"
  source: "https://github.com/helm/charts"
  method: "git"
  path: "stable/prometheus"
```

and to complete it, I wanted to add the `stable/prometheus` chart to it.  With this command line feature, I could do the following:

`$ fab add grafana --source https://github.com/helm/charts --path stable/grafana --type chart`

which would add this remote component to `component.json` such that it looks like the following:

```
name: "prometheus-grafana"
generator: "static"
path: "./manifests"
subcomponents:
- name: "grafana"
  type: "chart"
  source: "https://github.com/helm/charts"
  method: "git"
  path: "stable/grafana"
- name: "prometheus"
  type: "chart"
  source: "https://github.com/helm/charts"
  method: "git"
  path: "stable/prometheus"
```

Note that fetching the `source` will utilize the `git` method by default.

Likewise, the user can also add Fabrikate components.  For example, if they had the following `component.yaml`:

```
name: "cloud-native"
subcomponents:
  - name: "elasticsearch-fluentd-kibana"
    source: "https://github.com/timfpark/fabrikate-elasticsearch-fluentd-kibana"
    method: "git"
  - name: "istio"
    source: "https://github.com/timfpark/fabrikate-istio"
    method: "git"
  - name: "kured"
    source: "https://github.com/timfpark/fabrikate-kured"
    method: "git"
  - name: "jaeger"
    source: "https://github.com/bnookala/fabrikate-jaeger"
    method: "git"
```

And they wanted to add the `prometheus-grafana` component from the previous example to it, they could execute:

`$ fab add prometheus-grafana --source https://github.com/timfpark/fabrikate-prometheus-grafana`

And it would be added to their `component.yaml`:

```
name: "cloud-native"
subcomponents:
  - name: "elasticsearch-fluentd-kibana"
    source: "https://github.com/timfpark/fabrikate-elasticsearch-fluentd-kibana"
    method: "git"
  - name: "prometheus-grafana"
    source: "https://github.com/timfpark/fabrikate-prometheus-grafana"
    method: "git"
  - name: "istio"
    source: "https://github.com/timfpark/fabrikate-istio"
    method: "git"
  - name: "kured"
    source: "https://github.com/timfpark/fabrikate-kured"
    method: "git"
  - name: "jaeger"
    source: "https://github.com/bnookala/fabrikate-jaeger"
    method: "git"
```
